server:
  port: 8082
#  servlet:
#    context-path: /auth-server


mybatis:
  typeAliasesPackage: com.freeal.dao.entity
  mapperLocations: classpath:/mapper/*.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: jdbc:mysql://47.115.210.129:15003/CORAL?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: AIlA2023!?123
    driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis:
    type-aliases-package: com.freeal.bean

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  application:
    name: service-swagger
